name: My project deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update repository
        working-directory: /home/zaid2002/QA-Training-Project
        run: |
          git fetch origin main
          git reset --hard origin/main
      - name: NewMan Test
        working-directory: /home/zaid2002/QA-Training-Project
        run: newman run apitest.json

      - name: Ram status
        working-directory: /home/zaid2002/QA-Training-Project

        run: free -h
