name: My project deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update repository
        working-directory: /home/zaid2002/QA-Training-Project
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: NewMan Test
        working-directory: /home/zaid2002/QA-Training-Project/API
        run: |
          newman run apitest.json -e env.json -d users.csv -n 5 -r cli,htmlextra

      - name: Ram status
        run: free -h
